name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
- main
- synapse
- refs/heads/synapse
pr:
- main
- synapse

variables:
  solution: 'FhirToDataLake\*.sln'
  buildConfiguration: 'Release'
  buildPlatform: 'x64'
  major: 0
  minor: 3
  patch: 0
  buildnum: $[counter(format('{0}.{1}.{2}',variables['major'],variables['minor'], variables['patch']), 1)]
  version: $(major).$(minor).$(patch).$(buildnum)

stages:
- stage: Test
  jobs:
  - job: Test
    variables:
      STORAGE_CONNECTION_STRING: $(StorageConnectionString)
      SQL_USERNAME: $(SqlUsername)
      SQL_PASSWORD: $(SqlPassword)

    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.7'
      inputs:
        versionSpec: '3.7'

    - script: pip install pyodbc
      displayName: 'Install pyodbc'

    - task: PythonScript@0
      inputs:
        scriptSource: filePath
        scriptPath: '$(Build.SourcesDirectory)/E2E/E2E_Validator.py'
        arguments: --StorageConnectionString '$(STORAGE_CONNECTION_STRING)' --SqlUsername '$(SQL_USERNAME)' --SqlPassword '$(SQL_PASSWORD)'
