name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
- main
- synapse
- refs/heads/synapse
pr:
- main
- synapse

variables:
  solution: 'FhirToDataLake\*.sln'
  buildConfiguration: 'Release'
  buildPlatform: 'x64'
  major: 0
  minor: 3
  patch: 0
  buildnum: $[counter(format('{0}.{1}.{2}',variables['major'],variables['minor'], variables['patch']), 1)]
  version: $(major).$(minor).$(patch).$(buildnum)

stages:
- stage: Test
  jobs:
  - job: Test
    steps:
    - task: PythonScript@0
      inputs:
        scriptSource: inline
        script: |
          import os
          path = os.listdir(os.getcwd())
          for p in path:
              if os.path.isdir(p):
                  print(p)
        arguments: --world '$(Build.SourcesDirectory)'