name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
- main
- synapse
- refs/heads/synapse
pr:
- main
- synapse

variables:
  major: 0
  minor: 3
  patch: 0
  buildnum: $[counter(format('{0}.{1}.{2}',variables['major'],variables['minor'], variables['patch']), 1)]
  version: $(major).$(minor).$(patch).$(buildnum)

stages:
- stage: E2E
  pool:
    vmImage: windows-latest
  jobs:
  - job: E2ETest
    steps:
    - task: AzurePowerShell@5
      inputs: 
        azureSubscription: 'ResoluteOpenSource'
        azurePowerShellVersion: latestVersion
        ScriptType: inlineScript
        Inline: |
          Install-Module -Name Az.Synapse -Force -Scope CurrentUser
          .$(System.DefaultWorkingDirectory)/FhirToDataLake/scripts/Set-SynapseEnvironment.ps1  -SynapseWorkspaceName $(synapseWorkspaceName) -StorageName $(storageName)
      displayName: Set up EXTERNAL TABLEs and VIEWs on Synapse.

    - task: PythonScript@0
      inputs:
        scriptSource: filePath
        scriptPath: '$(Build.SourcesDirectory)/E2E/E2E_Validator.py'
        arguments: --SynapseWorkspaceName 'qwe' --FhirServerUrl $(fhirServerUrl) --Database "fhirdb" --SchemaCollectionDirectory  $(System.DefaultWorkingDirectory)/FhirToDataLake/data/schemas/
        
      env:
        STORAGE_CONNECTION_STRING: $(StorageConnectionString)
        SQL_USERNAME: $(SqlUsername)
        SQL_PASSWORD: $(SqlPassword)

    - task: NuGetAuthenticate@0
      displayName: NuGet Authenticate

    - task: NuGetToolInstaller@1
      displayName: Use NuGet 5.11
      inputs:
        versionSpec: 5.11

    - script: |
       docker pull healthplatformregistry.azurecr.io/fhir-analytics-data-source:v0.0.1
       docker run --rm -d -p 5000:5000 --name mock-data-source healthplatformregistry.azurecr.io/fhir-analytics-data-source:v0.0.1
      displayName: Start mock-data-source

    - task: AzurePowerShell@5
      inputs: 
        azureSubscription: 'ResoluteOpenSource'
        azurePowerShellVersion: latestVersion
        ScriptType: inlineScript
        Inline: |
          $templateParameters = @{
              appName = "$(appName)"
              fhirServerUrl = "$(fhirServerUrl)"
          }

          New-AzResourceGroupDeployment -ResourceGroupName $(resourceGroup) -TemplateFile $(System.DefaultWorkingDirectory)/FhirToDataLake/deploy/templates/FhirSynapsePipelineTemplate.json -TemplateParameterObject $templateParameters -Verbose
      displayName: Deploy Fhir Synapse sync pipeline

    - powershell: 'Start-Sleep -s 400'
      displayName: Delay 6 mins to fetch data from FHIR server

    - task: AzurePowerShell@5
      inputs: 
        azureSubscription: 'ResoluteOpenSource'
        azurePowerShellVersion: latestVersion
        ScriptType: inlineScript
        Inline: |
          Stop-AzFunctionApp -Name $(appName) -ResourceGroupName $(resourceGroup) -Force
      displayName: Stop function fetching data from FHIR server
    
    - task: Docker@2
      displayName: stop mock-data-source
      condition: succeededOrFailed()
      inputs:
        command: stop
        container: mock-data-source

    - task: AzureCLI@2
      inputs: 
        azureSubscription: 'ResoluteOpenSource'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $subscriptionId = az account show --query 'id' -o tsv

          $synapsePrincipalId = az synapse workspace show --name $(synapseWorkspaceName) --resource-group $(resourceGroup) --query 'identity.principalId' -o tsv
          $serviceConnectionPrincipalId = az account show --query 'user.name' -o tsv

          $storageScope = "/subscriptions/$($subscriptionId)/resourceGroups/$(resourceGroup)/providers/Microsoft.Storage/storageAccounts/$(storageName)"

          az role assignment create --role "Storage Blob Data Contributor" --assignee-object-id $synapsePrincipalId --scope $storageScope --assignee-principal-type ServicePrincipal
          az role assignment create --role "Storage Blob Data Contributor" --assignee $serviceConnectionPrincipalId --scope $storageScope
          # Wait 1 min in case the assignments don't enable.
          Start-Sleep -s 60
      displayName: Assign Azure roles for service connection and Synapse to the Storage
